name: Playwright-Test-Automation

on: 
  push:
    branches:
      - master

jobs:

  lighthouse:
    name: Run Lighthouse Accessibility Audit
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository
        uses: actions/checkout@v3

      - name: Run Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: https://www.amazon.in/
          configPath: ./configs/lighthouserc.json
          uploadArtifacts: true

      - name: Upload Lighthouse HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci/*.html

  test:
    name: Run Playwright - Tests
    runs-on: ubuntu-latest
    needs: lighthouse
    steps:
      - name: Check Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4 
        with:
          name: Playwright-Test-Results
          path: playwright-report/