name: Playwright-Test-Automation

on: 
  push:
    branches:
      - master

jobs:

  lighthouse:
    name: Run Lighthouse Accessibility Audit
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository
        uses: actions/checkout@v3

      - name: Start Lighthouse CI Audit
        run: echo "Lighthouse CI Audit Started"
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: lhci autorun ./config/lighthouse-score.json

      - name: Generate Lighthouse Summary
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: "https://www.amazon.in"
          outputDirectory: "./lighthouse-reports"



  test:
    name: Run Playwright - Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4 
        with:
          name: Playwright-Test-Results
          path: playwright-report/